# Generated by Django 5.1.2 on 2024-10-17 01:13

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumini',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('name_of_business', models.CharField(max_length=100, verbose_name='Name of Business')),
                ('business_address', models.CharField(max_length=100, verbose_name='Business Address')),
                ('business_city', models.CharField(max_length=100, verbose_name='Business City')),
                ('business_state', models.CharField(max_length=100, verbose_name='Business State')),
                ('business_zip', models.CharField(max_length=100, verbose_name='Business Zip')),
                ('business_phone', models.CharField(max_length=100, verbose_name='Business Phone')),
                ('business_email', models.EmailField(max_length=254, unique=True, verbose_name='Business Email')),
                ('business_website', models.CharField(max_length=100, verbose_name='Business Website')),
                ('business_description', models.TextField(max_length=100, verbose_name='Business Description')),
                ('business_category', models.CharField(max_length=100, verbose_name='Business Category')),
                ('alumini_discount', models.BooleanField(default=False, verbose_name='Alumini Discount')),
                ('alumini_discount_description', models.TextField(max_length=100, verbose_name='Alumini Discount Description')),
                ('business_logo_link', models.CharField(max_length=100, verbose_name='Business Logo Link')),
                ('user_id', models.CharField(max_length=100, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
