# Generated by Django 5.1.2 on 2024-10-22 21:43

import django.core.validators
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0005_alter_alumini_alumini_discount_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFromCsv',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='csv_files/', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='CSV File')),
            ],
        ),
        migrations.AlterField(
            model_name='alumini',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
